-- MySQL Script generated by MySQL Workbench
-- Fri Mar  9 22:01:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app` DEFAULT CHARACTER SET utf8 ;
USE `app` ;

-- -----------------------------------------------------
-- Table `app`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`users` ;

CREATE TABLE IF NOT EXISTS `app`.`users` (
  `id_user` int(11) NOT NULL AUTO_INCREMENT,
  `firstname` varchar(100) NOT NULL,
  `lastname` varchar(100) NOT NULL,
  `email` varchar(255) NOT NULL,
  `pwd` char(60) NOT NULL,
  `token` char(32) NOT NULL,
  `age` tinyint(4) NOT NULL,
  `status` tinyint(4) NOT NULL DEFAULT '0',
  `date_inserted` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `app`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`categories` ;

CREATE TABLE IF NOT EXISTS `app`.`categories` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(30) NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`products` ;

CREATE TABLE IF NOT EXISTS `app`.`products` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(60) NULL,
  `categories_idcategory` INT NOT NULL,
  `description` LONGTEXT NULL,
  `price` FLOAT NULL,
  `ram` VARCHAR(20) NULL,
  PRIMARY KEY (`id_product`),
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`categories_idcategory`)
    REFERENCES `app`.`categories` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_products_categories1_idx` ON `app`.`products` (`categories_idcategory` ASC);


-- -----------------------------------------------------
-- Table `app`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`images` ;

CREATE TABLE IF NOT EXISTS `app`.`images` (
  `id_image` INT NOT NULL AUTO_INCREMENT,
  `image_name` VARCHAR(75) NULL,
  `path` varchar(255) NOT NULL,
  `products_idproduct` INT NOT NULL,
  PRIMARY KEY (`id_image`),
  CONSTRAINT `fk_images_products`
    FOREIGN KEY (`products_idproduct`)
    REFERENCES `app`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_images_products_idx` ON `app`.`images` (`products_idproduct` ASC);


-- -----------------------------------------------------
-- Table `app`.`colors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`colors` ;

CREATE TABLE IF NOT EXISTS `app`.`colors` (
  `id_color` INT NOT NULL AUTO_INCREMENT,
  `color_hexa` VARCHAR(35) NULL,
  `products_idproduct` INT NOT NULL,
  PRIMARY KEY (`id_color`),
  CONSTRAINT `fk_colors_products1`
    FOREIGN KEY (`products_idproduct`)
    REFERENCES `app`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_colors_products1_idx` ON `app`.`colors` (`products_idproduct` ASC);


-- -----------------------------------------------------
-- Table `app`.`capacities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`capacities` ;

CREATE TABLE IF NOT EXISTS `app`.`capacities` (
  `id_capacity` INT NOT NULL AUTO_INCREMENT,
  `capacity_number` INT NULL,
  `products_idproduct` INT NOT NULL,
  `additional_price` FLOAT NULL,
  PRIMARY KEY (`id_capacity`),
  CONSTRAINT `fk_capacities_products1`
    FOREIGN KEY (`products_idproduct`)
    REFERENCES `app`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_capacities_products1_idx` ON `app`.`capacities` (`products_idproduct` ASC);


-- -----------------------------------------------------
-- Table `app`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`comments` ;

CREATE TABLE IF NOT EXISTS `app`.`comments` (
  `id_comment` INT NOT NULL AUTO_INCREMENT,
  `comment` LONGTEXT NULL,
  `users_idusers` INT NOT NULL,
  `products_idproduct` INT NOT NULL,
  PRIMARY KEY (`id_comment`),
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `app`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_products1`
    FOREIGN KEY (`products_idproduct`)
    REFERENCES `app`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_comments_users1_idx` ON `app`.`comments` (`users_idusers` ASC);

CREATE INDEX `fk_comments_products1_idx` ON `app`.`comments` (`products_idproduct` ASC);


-- -----------------------------------------------------
-- Table `app`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`orders` ;

CREATE TABLE IF NOT EXISTS `app`.`orders` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `tracking_number` VARCHAR(15) NULL,
  `status` VARCHAR(45) NULL,
  `users_idusers` INT NOT NULL,
  `products_idproduct` INT NOT NULL,
  PRIMARY KEY (`id_order`),
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `app`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_products1`
    FOREIGN KEY (`products_idproduct`)
    REFERENCES `app`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_orders_users1_idx` ON `app`.`orders` (`users_idusers` ASC);

CREATE INDEX `fk_orders_products1_idx` ON `app`.`orders` (`products_idproduct` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
