-- MySQL Script generated by MySQL Workbench
-- Thu Apr  5 17:59:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app` DEFAULT CHARACTER SET utf8 ;
USE `app` ;

-- -----------------------------------------------------
-- Table `app`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `users` (
  `id_user` int(11) NOT NULL AUTO_INCREMENT,
  `firstname` varchar(100) NOT NULL,
  `lastname` varchar(100) NOT NULL,
  `sexe` tinyint(1) DEFAULT NULL,
  `birthday_date` date DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `zip_code` tinyint(5) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `pwd` char(60) NOT NULL,
  `token` char(32) NOT NULL,
  `status` tinyint(4) NOT NULL DEFAULT '0',
  `date_inserted` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_user`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;


-- -----------------------------------------------------
-- Table `app`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app`.`categories` (
  `id_category` INT NOT NULL,
  `category_name` VARCHAR(30) NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app`.`products` (
  `id_product` INT NOT NULL,
  `product_name` VARCHAR(60) NULL,
  `categories_idcategory` INT NOT NULL,
  `description` LONGTEXT NULL,
  `price` FLOAT NULL,
  `ram` VARCHAR(20) NULL,
  PRIMARY KEY (`id_product`),
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`categories_idcategory`)
    REFERENCES `app`.`categories` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app`.`images` (
  `id_image` INT NOT NULL,
  `image_name` VARCHAR(75) NULL,
  `products_idproduct` INT NOT NULL,
  PRIMARY KEY (`id_image`),
  CONSTRAINT `fk_images_products`
    FOREIGN KEY (`products_idproduct`)
    REFERENCES `app`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app`.`colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app`.`colors` (
  `id_color` INT NOT NULL,
  `color_hexa` VARCHAR(35) NULL,
  `products_idproduct` INT NOT NULL,
  PRIMARY KEY (`id_color`),
  CONSTRAINT `fk_colors_products1`
    FOREIGN KEY (`products_idproduct`)
    REFERENCES `app`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app`.`capacities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app`.`capacities` (
  `id_capacity` INT NOT NULL,
  `capacity_number` INT NULL,
  `products_idproduct` INT NOT NULL,
  `additional_price` FLOAT NULL,
  PRIMARY KEY (`id_capacity`),
  CONSTRAINT `fk_capacities_products1`
    FOREIGN KEY (`products_idproduct`)
    REFERENCES `app`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app`.`comments` (
  `id_comment` INT NOT NULL,
  `comment` LONGTEXT NULL,
  `users_idusers` INT NOT NULL,
  `products_idproduct` INT NOT NULL,
  PRIMARY KEY (`id_comment`),
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `app`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_products1`
    FOREIGN KEY (`products_idproduct`)
    REFERENCES `app`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app`.`orders` (
  `id_order` INT NOT NULL,
  `tracking_number` VARCHAR(15) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_order`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app`.`carts` (
  `id_cart` INT NOT NULL,
  `capacities_id_capacity` INT NOT NULL,
  `products_id_product` INT NOT NULL,
  `colors_id_color` INT NOT NULL,
  `users_id_user` INT NOT NULL,
  `orders_id_order` INT NOT NULL,
  PRIMARY KEY (`id_cart`),
  CONSTRAINT `fk_Cart_capacities1`
    FOREIGN KEY (`capacities_id_capacity`)
    REFERENCES `app`.`capacities` (`id_capacity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cart_products1`
    FOREIGN KEY (`products_id_product`)
    REFERENCES `app`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cart_colors1`
    FOREIGN KEY (`colors_id_color`)
    REFERENCES `app`.`colors` (`id_color`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cart_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `app`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carts_orders1`
    FOREIGN KEY (`orders_id_order`)
    REFERENCES `app`.`orders` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
